version: '3.9'

services:

  backend:
    build: ./backend
    container_name: backend_container
    ports: 
      - 3020:3020
    volumes:
      - ./backend:/app/back
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3020"]
      timeout: 10s
      retries: 5
    depends_on:
      bancodedados:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports: 
      - 3030:3030
    volumes:
      - ./frontend:/app/front
    depends_on:
        backend:
          condition: service_healthy
    command: npm start

  bancodedados:
    container_name: bancodedados_mysql 
    image: mysql:8.0.21
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", '-h', 'localhost']
      timeout: 10s
      retries: 5